version: "3"

services:
  inventory-service:
    hostname: inventory-host
    build:
      context: .
      dockerfile: ./inventory-service/Dockerfile
    ports:
      - "4001:4001"
    networks:
      - wpg-network
      - inventory-network
    depends_on:
      - inventory-database
  inventory-database:
    hostname: inventory-database-host
    image: postgres:8.4
    ports:
      - "5432:5432"
    networks:
      - inventory-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    restart: on-failure
  customer-service:
    hostname: customer
    build:
      context: .
      dockerfile: ./customer-service/Dockerfile
    ports:
      - "4002:4002"
    networks:
      - wpg-network
  order-service:
    hostname: order
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "4003:4003"
    networks:
      - wpg-network
networks:
  wpg-network:
    driver: bridge
  inventory-network:
    driver: bridge
